# 1)

In [4]:
class Rectangle:
    def __init__(self,x,h):
        self.x = x
        self.h = h
        
    def getArea(self):
        return (self.x*self.h)/2

In [6]:
x = Rectangle(2,4)
x.getArea()

4.0

# 2)

In [18]:
class Circle:
    def __init__(self, r):
        self.r = r
    
    def getArea(self):
            return 3.14*(self.r**2) 
        
    def getPerimeter(self):
            return 3.14*self.r

In [22]:
c = Circle(2)
c.getArea()

12.56

In [23]:
c.getPerimeter()

6.28

# 3)

In [6]:
import numpy as np

In [7]:
class Person:
    def __init__(self,name,age,sex,weight,height):
        self.name = name
        self.age = age
        self.sex = sex
        self.weight = weight
        self.height = height
        
        self.isOverage()
        self.printData()
        self.generateID()
    
    def isOverage(self):
        if self.age > 18:
            return True
        else: return False
        
    def printData(self):
        print(self.name)
        print(self.age)
        print(self.sex)
        print(self.weight)
        print(self.height)
        
    def generateID(self):
        self.id = np.random.randint(0,10,8)
        print(self.id)

In [8]:
i = Person('Gastón',20,'M','80',1.88)

Gastón
20
M
80
1.88
[1 1 3 4 0 2 1 6]


# 4)

In [9]:
import datetime

In [62]:
class Student(Person):
    def __init__(self,name,age,sex,weight,height,courseName,entryYear,subjectCount,subjectPassed):
        super().__init__(name,age,sex,weight,height)
        self.courseName = courseName
        self.entryYear = entryYear
        self.subjectCount = subjectCount
        self.subjectPassed = subjectPassed
        
    def coursePercent(self):
        return self.subjectPassed / self.subjectCount
        
    def ageAtEntry(self):
        return self.age - ((datetime.datetime.now()).year - self.entryYear)
    
    def toDict(self):
        return {
            'name': self.name,
            'course': self.courseName
        }
        

In [11]:
i = Student('Gastón',20,'M','80',1.88,'Ingeniería en Sistemas',2017,41,25)

Gastón
20
M
80
1.88
[6 2 7 0 2 8 7 9]


In [12]:
i.coursePercent()
i.ageAtEntry()

17

# 5)

In [13]:
import pandas as pd

In [63]:
s1 = Student('Gastón',20,'M','80',1.88,'Ingeniería en Sistemas',2017,41,25)
s2 = Student('Martín',21,'M','85',1.78,'Ingeniería en Sistemas',2017,41,25)
s3 = Student('Lucía',19,'M','85',1.78,'Ingeniería Civil',2017,35,15)
s4 = Student('Marta',25,'M','85',1.78,'Ingeniería Química',2017,34,31)
students = [s1,s2,s3,s4]

Gastón
20
M
80
1.88
[8 7 4 7 1 3 5 5]
Martín
21
M
85
1.78
[5 4 8 6 8 3 1 8]
Lucía
19
M
85
1.78
[2 7 0 5 2 3 0 2]
Marta
25
M
85
1.78
[4 7 7 2 0 5 8 2]


In [69]:
df = pd.DataFrame.from_records([s.toDict() for s in students])
df

name                  course
0  Gastón  Ingeniería en Sistemas
1  Martín  Ingeniería en Sistemas
2   Lucía        Ingeniería Civil
3   Marta      Ingeniería Química

In [76]:
sCount = (df.groupby('course')).count()
sCount

name
course                      
Ingeniería Civil           1
Ingeniería Química         1
Ingeniería en Sistemas     2

# 6)

In [7]:
import datetime

In [20]:
class Person:
    def __init__(self,fNac):
        self.fNac = fNac
        
    def getAge(self):
        return ((datetime.datetime.now() - self.fNac).days) /365

In [21]:
p = Person(datetime.datetime(1999,4,3))

In [22]:
p.getAge()

20.98904109589041